/* Generated By:JavaCC: Do not edit this line. CMMTreeConstants.java Version 5.0 */
package CMMParser;

public interface CMMTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTSTARTSTATEMENT = 2;
  public int JJTSTATEMENT = 3;
  public int JJTSEQUENCESTATEMENT = 4;
  public int JJTDECLARATION = 5;
  public int JJTCOPY = 6;
  public int JJTIFSTATEMENT = 7;
  public int JJTELSESTATEMENT = 8;
  public int JJTASSIGN = 9;
  public int JJTCONDITION = 10;
  public int JJTTERM = 11;
  public int JJTUNARY = 12;
  public int JJTWHILE = 13;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "startStatement",
    "Statement",
    "SequenceStatement",
    "declaration",
    "copy",
    "IfStatement",
    "ElseStatement",
    "assign",
    "Condition",
    "term",
    "unary",
    "While",
  };
}
/* JavaCC - OriginalChecksum=33dc7a61d61ca59225b8467374b29f8b (do not edit this line) */
